"""Deterministic language surfaces.

The pilot keeps answer generation deterministic.  An answer-blind LLM may
paraphrase question slots later, but it must not see answer values.
"""

from __future__ import annotations

import re

# Chinese names are an explicit ontology contract, not ad-hoc string
# replacements.  The table covers every raw category occurring in the strict
# 2026-07-16 pilot sweeps, plus a few common aliases used by older bundles.
# Names prefer visually identifiable, mainland-Chinese terms and preserve
# useful distinctions (for example, 吊柜/地柜 and 固定窗/可开启窗).
CATEGORY_ZH = {
    "arbor": "花架",
    "armchair": "扶手椅",
    "background": "背景",
    "bar": "吧台",
    "baseboard": "踢脚线",
    "bathtub": "浴缸",
    "bed": "床",
    "bed_screen": "床旁屏风",
    "beer_glass": "啤酒杯",
    "beer_tap": "啤酒龙头",
    "bench": "长凳",
    "bench_press_machine": "卧推机",
    "blackboard": "黑板",
    "bookcase": "书架",
    "booth": "卡座",
    "bottle_of_tea": "瓶装茶",
    "bottom_cabinet": "地柜",
    "bottom_cabinet_no_top": "无台面地柜",
    "boulder": "巨石",
    "breakfast_table": "餐桌",
    "burner": "灶头",
    "bush": "灌木",
    "cabinet": "柜子",
    "candy_dispenser_shelf": "糖果分配架",
    "car": "汽车",
    "carpet": "地毯",
    "cash_register": "收银机",
    # RGB supports object category/shape, not the wood species encoded in the
    # asset filename.  Keep the model-facing surface visually decidable.
    "cedar_chest": "木箱",
    "ceiling": "天花板",
    "ceiling_air_conditioner": "吊顶式空调",
    "ceiling_fan": "吊扇",
    "ceiling_mounted_basketball_hoop": "吊装篮球架",
    "ceiling_mounted_projector": "吊装投影仪",
    "ceiling_rack": "顶部吊架",
    "ceilings": "天花板",
    "chair": "椅子",
    "chandelier": "吊灯",
    "charcoal_grill": "炭烤炉",
    "checkout_counter": "收银台",
    "clothes_dryer": "衣物烘干机",
    "clothesline_pole": "晾衣杆",
    "coatrack": "衣帽架",
    "coffee_maker": "咖啡机",
    "coffee_table": "咖啡桌",
    "commercial_kitchen_shelf": "商用厨房置物架",
    "commercial_kitchen_sink": "商用厨房水槽",
    "commercial_kitchen_table": "商用厨房操作台",
    "conference_table": "会议桌",
    "console_table": "玄关桌",
    "countertop": "操作台面",
    "couch": "沙发",
    "crib": "婴儿床",
    "cubicle": "办公隔间",
    "decorative_sign": "装饰标牌",
    "deep_fryer": "油炸锅",
    "desk": "书桌",
    "dessert_stand": "甜品展示架",
    "dish_rack_cart": "餐具架推车",
    "dishwasher": "洗碗机",
    "display_case": "展示柜",
    "display_fridge": "展示冷藏柜",
    "door": "门",
    "downlight": "筒灯",
    "dresser": "斗柜",
    "drink_dispenser": "饮料分配机",
    "drinking_fountain": "饮水台",
    "driveway": "车道",
    "drop_in_sink": "嵌入式水槽",
    "dry_food_dispenser_shelf": "干货分配架",
    "eames_chair": "伊姆斯椅",
    "electric_switch": "墙壁开关",
    "elevator_door": "电梯门",
    "elliptical_machine": "椭圆机",
    "espresso_machine": "意式咖啡机",
    "exercise_bike": "健身车",
    "fire_alarm": "火灾报警器",
    "fire_extinguisher": "灭火器",
    "fire_sprinkler": "消防喷淋头",
    "fixed_window": "固定窗",
    "flat_bench": "平板训练凳",
    "flat_top_grill": "平面煎台",
    "floor": "地面",
    "floor_lamp": "落地灯",
    "floors": "地面",
    "folderal": "装饰摆件",
    "free_weight_rack": "自由重量架",
    "freezer": "冷冻柜",
    "fridge": "冰箱",
    "furniture_sink": "带柜水槽",
    "garage_door": "车库门",
    "garden_chair": "户外椅",
    "garden_light": "庭院灯",
    "gas_fireplace": "燃气壁炉",
    "grandfather_clock": "落地座钟",
    "grocery_fridge": "商超冷藏柜",
    "grocery_shelf": "商品货架",
    "grocery_sign": "商超指示牌",
    "guitar": "吉他",
    "gym_mat": "健身垫",
    "hall_tree": "门厅衣帽架",
    "hammam_bench": "蒸汽浴室长凳",
    "hammock": "吊床",
    "hamper": "洗衣篮",
    "hand_dryer": "烘手机",
    "handle": "把手",
    "handset": "电话听筒",
    "hanging": "壁挂装饰",
    "hanging_banners": "悬挂横幅",
    "hanging_plant": "垂吊植物",
    "hingeless_jar": "无铰盖罐",
    "hook": "挂钩",
    "hospital_bed": "病床",
    "hot_tub": "热水浴池",
    "information_bulletin": "信息公告栏",
    "jukebox": "自动点唱机",
    "l_shaped_handle": "L形把手",
    "lab_exhaust_hood": "实验室通风柜",
    "lab_table": "实验台",
    "ladder": "梯子",
    "laptop": "笔记本电脑",
    "lawn": "草坪",
    "locker": "储物柜",
    "loudspeaker": "扬声器",
    "magazine_stand": "杂志架",
    "mailbox": "邮箱",
    "makeup_mirror": "化妆镜",
    "map": "地图",
    "massage_bed": "按摩床",
    "menu": "菜单",
    "metal_bottom_cabinet": "金属地柜",
    "microwave": "微波炉",
    "mirror": "镜子",
    "monitor": "显示器",
    "motion_sensor": "运动传感器",
    "multi_station_furniture_sink": "多工位带柜水槽",
    "multi_station_tabletop_sink": "多工位台上洗手池",
    "multi_station_wall_mounted_sink": "多工位壁挂式洗手池",
    "music_stool": "琴凳",
    "nightstand": "床头柜",
    "oden_cooker": "关东煮机",
    "openable_window": "可开启窗",
    "ottoman": "脚凳",
    "oven": "烤箱",
    "packing_box": "包装箱",
    "painting": "绘画作品",
    "paper_lantern": "纸灯笼",
    "paper_towel_dispenser": "擦手纸分配器",
    "parallel_bars": "双杠",
    "paver": "铺路砖",
    "pay_phone": "公用电话",
    "pedestal": "基座",
    "pedestal_sink": "立柱式洗手盆",
    "pedestal_table": "单柱桌",
    "periodic_table": "元素周期表",
    "phonograph_record": "黑胶唱片",
    "photocopier": "复印机",
    "piano": "钢琴",
    "picture": "挂画",
    "pillar": "立柱",
    "pillow": "枕头",
    "playground": "游乐场",
    "pommel_horse": "鞍马",
    "pool_table": "台球桌",
    "portrait": "人像画",
    "pot_plant": "盆栽",
    "projection_screen": "投影幕布",
    "public_trash_can": "公共垃圾桶",
    "radiator": "暖气片",
    "rail_fence": "栅栏",
    "railing": "护栏",
    "range_hood": "油烟机",
    "reception_desk": "前台",
    "recreational_vehicle": "房车",
    "rectangular_light": "长方形顶灯",
    "rocking_chair": "摇椅",
    "roof": "屋顶",
    "room_divider": "隔断",
    "room_light": "室内灯",
    "room_ventilator": "房间通风口",
    "sauna_bench": "桑拿房长凳",
    "sauna_heater": "桑拿炉",
    "scoreboard": "记分牌",
    "security_camera": "监控摄像头",
    "serving_cart": "餐车",
    "shelf": "置物架",
    "shopping_cart": "购物车",
    "shower": "淋浴设备",
    "shower_stall": "淋浴间",
    "showerhead": "花洒",
    "signpost": "标志柱",
    "skeletal_frame": "骨架结构",
    "sliding_door": "推拉门",
    "snack_rack": "零食货架",
    "soap_dispenser": "皂液器",
    "soda_cup": "汽水杯",
    "sofa": "沙发",
    "spotlight": "射灯",
    "square_light": "方形顶灯",
    "stadium_stand": "体育场看台",
    "stairs": "楼梯",
    "stand": "支架",
    "standing_loudspeaker": "落地音箱",
    "standing_mirror": "落地镜",
    "standing_tv": "电视",
    "statue": "雕像",
    "stove": "炉灶",
    "straight_chair": "直背椅",
    "structural_element": "建筑构件",
    "swimming_pool": "游泳池",
    "swing": "秋千",
    "swing_set": "秋千架",
    "swivel_chair": "转椅",
    "table": "桌子",
    "table_lamp": "台灯",
    "tabletop_sink": "台上盆",
    "taboret": "圆凳",
    "toilet": "马桶",
    "toilet_paper_dispenser": "卫生纸分配器",
    "toilet_paper_holder": "卫生纸架",
    "top_cabinet": "吊柜",
    "towel_rack": "毛巾架",
    "track_light": "轨道灯",
    "trash_can": "垃圾桶",
    "treadmill": "跑步机",
    "tree": "树",
    "turnstile": "闸机",
    "tv": "电视",
    "umbrella_rack": "雨伞架",
    "urinal": "小便池",
    "vending_machine": "自动售货机",
    "vine": "藤蔓",
    "volleyball_net": "排球网",
    "wall": "墙面",
    "wall_clock": "挂钟",
    "wall_mounted_light": "壁灯",
    "wall_mounted_loudspeaker": "壁挂扬声器",
    "wall_mounted_sink": "壁挂式洗手盆",
    "wall_mounted_soap_dispenser": "壁挂式皂液器",
    "wall_mounted_tv": "壁挂电视",
    "wall_nail": "墙钉",
    "wall_socket": "墙壁插座",
    "walls": "墙面",
    "wardrobe": "衣柜",
    "washer": "洗衣机",
    "water_cooler": "饮水机",
    "water_glass": "水杯",
    "whiteboard": "白板",
    "window": "窗户",
    "window_blind": "百叶窗",
    "wine_fridge": "葡萄酒冷藏柜",
    "wood_fireplace": "燃木壁炉",
}

RELATION_ZH = {
    "left_of": "左侧",
    "right_of": "右侧",
    "in_front_of": "前方",
    "behind": "后方",
    "front_left": "左前方",
    "front_right": "右前方",
    "back_left": "左后方",
    "back_right": "右后方",
}


def entity_name(raw_label: str) -> str:
    key = raw_label.strip().lower().replace(" ", "_")
    if key in CATEGORY_ZH:
        return CATEGORY_ZH[key]
    return raw_label.replace("_", " ").strip()


def localize_categories(text: str) -> str:
    """Replace raw ontology tokens in a natural-language surface with Chinese."""

    localized = text
    for key in sorted(CATEGORY_ZH, key=len, reverse=True):
        translated = CATEGORY_ZH[key]
        surfaces = {key, key.replace("_", " ")}
        for surface in sorted(surfaces, key=len, reverse=True):
            localized = re.sub(
                rf"(?<![A-Za-z0-9_]){re.escape(surface)}(?![A-Za-z0-9_])",
                translated,
                localized,
                flags=re.IGNORECASE,
            )
    return localized


def relation_name(value: str) -> str:
    return RELATION_ZH.get(value, value.replace("_", " "))


def view_number(view_id: str) -> int:
    match = re.fullmatch(r"view-(\d+)", view_id)
    if not match:
        raise ValueError(f"invalid view id: {view_id}")
    return int(match.group(1)) + 1


def normalize_space(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()
