"""Chinese lexicon for OmniGibson categories observed in the static-m2 sweep.

Categories absent from this map are excluded from question generation; the
compiler reports coverage instead of inventing names.  Structural categories
are never used as question referents.
"""

from __future__ import annotations

STRUCTURAL_LABELS = {
    "background",
    "walls",
    "floors",
    "ceilings",
    "structural_element",
    "railing",
    "stairs",
    "arbor",
    "doorframe",
    "track_light",
    "room_light",
    "square_light",
    "downlight",
    "electric_switch",
    "wall_socket",
    "fire_sprinkler",
    "openable_window",
    "fixed_window",
    "window",
}

CATEGORY_NAMES_ZH: dict[str, str] = {
    "armchair": "扶手椅",
    "bar": "吧台",
    "bathtub": "浴缸",
    "bench": "长凳",
    "bed": "床",
    "beer_tap": "啤酒龙头",
    "bookcase": "书架",
    "bottom_cabinet": "矮柜",
    "bottom_cabinet_no_top": "无台面地柜",
    "breakfast_table": "餐桌",
    "bush": "灌木",
    "burner": "灶眼",
    "candy_dispenser_shelf": "糖果货架",
    "carpet": "地毯",
    "cash_register": "收银机",
    "cedar_chest": "木箱",
    "ceiling_air_conditioner": "吸顶空调",
    "ceiling_mounted_basketball_hoop": "吊装篮球架",
    "ceiling_rack": "吊架",
    "chandelier": "吊灯",
    "checkout_counter": "收银台",
    "clothes_dryer": "烘干机",
    "coffee_maker": "咖啡机",
    "coffee_table": "咖啡桌",
    "commercial_kitchen_table": "商用厨房工作台",
    "conference_table": "会议桌",
    "console_table": "玄关桌",
    "countertop": "操作台面",
    "cubicle": "办公隔间",
    "desk": "书桌",
    "dessert_stand": "甜品架",
    "dishwasher": "洗碗机",
    "display_case": "展示柜",
    "door": "门",
    "drinking_fountain": "饮水台",
    "drop_in_sink": "嵌入式水槽",
    "dry_food_dispenser_shelf": "干货货架",
    "eames_chair": "休闲椅",
    "elevator_door": "电梯门",
    "fire_alarm": "火警报警器",
    "fire_extinguisher": "灭火器",
    "flat_top_grill": "平板烤炉",
    "floor_lamp": "落地灯",
    "fridge": "冰箱",
    "furniture_sink": "带柜水槽",
    "gas_fireplace": "燃气壁炉",
    "garden_chair": "户外椅",
    "garden_light": "庭院灯",
    "grocery_fridge": "商用冷柜",
    "grocery_shelf": "杂货货架",
    "gym_mat": "体操垫",
    "hand_dryer": "烘手机",
    "handset": "电话听筒",
    "hot_tub": "热水浴池",
    "jukebox": "点唱机",
    "lawn": "草坪",
    "laptop": "笔记本电脑",
    "locker": "储物柜",
    "loudspeaker": "音箱",
    "makeup_mirror": "化妆镜",
    "microwave": "微波炉",
    "mirror": "镜子",
    "multi_station_furniture_sink": "多工位洗手台",
    "nightstand": "床头柜",
    "oden_cooker": "关东煮机",
    "ottoman": "脚凳",
    "oven": "烤箱",
    "painting": "油画",
    "packing_box": "包装箱",
    "paper_towel_dispenser": "纸巾分配器",
    "parallel_bars": "双杠",
    "pay_phone": "公用电话",
    "paver": "铺路砖",
    "pedestal_sink": "立柱洗手池",
    "pedestal_table": "独脚圆桌",
    "piano": "钢琴",
    "pillar": "立柱",
    "picture": "挂画",
    "portrait": "肖像画",
    "pot_plant": "盆栽",
    "playground": "游乐设施",
    "public_trash_can": "公共垃圾桶",
    "radiator": "暖气片",
    "rail_fence": "栏杆围栏",
    "range_hood": "抽油烟机",
    "reception_desk": "接待台",
    "room_divider": "屏风隔断",
    "scoreboard": "记分牌",
    "security_camera": "监控摄像头",
    "shelf": "置物架",
    "shower_stall": "淋浴间",
    "signpost": "指示牌",
    "snack_rack": "零食货架",
    "soap_dispenser": "皂液器",
    "sofa": "沙发",
    "stand": "立架",
    "standing_loudspeaker": "立式音箱",
    "standing_mirror": "立式穿衣镜",
    "standing_tv": "立式电视",
    "stadium_stand": "看台",
    "stove": "炉灶",
    "straight_chair": "直背椅",
    "swivel_chair": "转椅",
    "swing_set": "秋千架",
    "table_lamp": "台灯",
    "toilet": "马桶",
    "toilet_paper_dispenser": "卷纸架",
    "top_cabinet": "吊柜",
    "towel_rack": "毛巾架",
    "trash_can": "垃圾桶",
    "tree": "树",
    "turnstile": "闸机",
    "volleyball_net": "排球网",
    "wall_clock": "挂钟",
    "wall_mounted_sink": "壁挂洗手池",
    "wall_mounted_tv": "壁挂电视",
    "washer": "洗衣机",
    "water_cooler": "饮水机",
    "wine_fridge": "酒柜",
    "wood_fireplace": "壁炉",
}

RELATION_ZH = {
    "left_of": "左侧",
    "right_of": "右侧",
    "in_front_of": "前方",
    "behind": "后方",
}

QUADRANT_ZH = {
    "front-left": "左前方",
    "front-right": "右前方",
    "back-left": "左后方",
    "back-right": "右后方",
}
