const DATA_URL='data/transform_pilot.v1.json';
const state={data:null,records:[],filtered:[],current:null,arm:'grounded_cot'};
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=value=>value==null?'—':`${(100*Number(value)).toFixed(1)}%`;
const taskName=id=>id==='self_rotation_query.v1'?'Self-Rotation':id.includes('cross_view')?'Among · Cross-view Relation':'Among · Object Perspective';
const scopeName=scope=>scope==='all'?'全量表面':scope==='balanced_all'?'事实去重平衡':'冻结测试';
const modelName=id=>id?.includes('1.5')?'SenseNova 1.5':id?.includes('1.1')?'SenseNova 1.1':id??'Model';
const verdict=o=>o?.correct?'答案正确':o?.semantic_correct?'语义正确':'答案错误';
function renderModelOutputs(r){
  const outputs=Object.entries(r.model_outputs??{}).sort(([a],[b])=>modelName(a).localeCompare(modelName(b)));
  $('output-arm-label').textContent=state.arm==='grounded_cot'?'Grounded-CoT 提示':'Answer-only 提示';
  if(!outputs.length){$('model-output-grid').innerHTML='<div class="model-output-empty">该样本没有已冻结的模型输出。</div>';return}
  $('model-output-grid').innerHTML=outputs.map(([model,arms])=>{
    const o=arms[state.arm];
    if(!o)return `<article class="model-output-card missing"><div class="model-output-head"><strong>${esc(modelName(model))}</strong><span>未评测</span></div></article>`;
    const trace=o.trace_format??{};
    const traceText=state.arm==='grounded_cot'?`cue ${trace.has_cue?'✓':'×'} · transform ${trace.has_transform?'✓':'×'} · answer ${trace.has_answer?'✓':'×'}`:'只要求答案';
    return `<article class="model-output-card ${o.correct?'correct':'wrong'}">
      <div class="model-output-head"><strong>${esc(modelName(model))}</strong><span>${esc(verdict(o))}</span></div>
      <pre>${esc(o.response||'(空输出)')}</pre>
      <div class="model-output-meta"><span>预测 ${esc(o.prediction??'—')} · ${esc(o.prediction_semantic_label??'未解析')}</span><span>真值 ${esc(o.ground_truth??'—')} · ${esc(o.ground_truth_label??'—')}</span><span>${esc(traceText)}</span></div>
    </article>`;
  }).join('');
}
function metrics(){const r=state.data.report,c=r.counts,a=r.audit;const items=[['独立几何事实',c.unique_base_facts],['T3 训练表面',c.self_rotation_records],['Among 完整族',c.complete_among5_families??0],['平衡训练样本',c.balanced_by_split?.train??'—'],['自动审计',a.status.toUpperCase()]];$('metrics').innerHTML=items.map(([k,v])=>`<div class="metric"><strong>${esc(v)}</strong><span>${esc(k)}</span></div>`).join('');const ready=r.status==='data_ready';$('readiness').textContent=ready?'MACHINE READY':'COLLECTING / REVIEW';$('readiness').className=`status-chip ${ready?'pass':'blocked'}`}
function initFilters(){const tasks=[...new Set(state.records.map(r=>r.task_id))];$('task-filter').innerHTML='<option value="all">全部任务</option>'+tasks.map(t=>`<option value="${esc(t)}">${esc(taskName(t))}</option>`).join('');$('task-filter').onchange=filterRecords;filterRecords()}
function filterRecords(){const task=$('task-filter').value;state.filtered=state.records.filter(r=>task==='all'||r.task_id===task);$('sample-count').textContent=`${state.filtered.length} showcase`;$('sample-select').innerHTML=state.filtered.map(r=>`<option value="${r.record_id}">${esc(taskName(r.task_id))} · ${esc(r.scene_id)}${r.variant_id?' · '+esc(r.variant_id):''}</option>`).join('');$('sample-select').onchange=()=>selectRecord($('sample-select').value);if(state.filtered.length)selectRecord(state.filtered[0].record_id)}
function selectRecord(id){state.current=state.records.find(r=>r.record_id===id);render()}
function variantTabs(r){if(!r.variant_id){$('variant-tabs').innerHTML='';return}const siblings=state.records.filter(x=>x.family_id===r.family_id&&x.query_index===r.query_index&&x.task_id===r.task_id);$('variant-tabs').innerHTML=siblings.map(x=>`<button class="${x.record_id===r.record_id?'active':''}" data-id="${x.record_id}">${esc(x.variant_id)} · ${esc(x.answer.text)}</button>`).join('');$('variant-tabs').querySelectorAll('button').forEach(b=>b.onclick=()=>selectRecord(b.dataset.id))}
function render(){const r=state.current;if(!r)return;variantTabs(r);$('record-title').textContent=taskName(r.task_id);$('image-grid').innerHTML=r.model_input.images.map((src,i)=>`<figure><img src="${esc(src)}" alt="view ${i+1}" loading="lazy"><figcaption>IMAGE ${String(i+1).padStart(2,'0')}</figcaption></figure>`).join('');$('system-text').textContent=r.model_input.system;$('question-text').textContent=r.model_input.question;$('assistant-target').textContent=r.targets[state.arm];$('op-graph').innerHTML=r.operation_graph.nodes.map((n,i)=>`${i?'<span class="op-arrow">→</span>':''}<span class="op-node">${esc(n)}</span>`).join('');$('record-meta').innerHTML=[['record',r.record_id],['scene',r.scene_id],['split',r.split],['base fact',r.base_fact_id],['variant',r.variant_id??'—']].map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('');const t=r.grounded_trace;$('trace-panel').innerHTML=`<div class="trace-step"><b>CUE · ${t.cue.claims.length} claims</b>${esc(t.cue.surface)}</div><div class="trace-step transform"><b>TRANSFORM · ${t.transform.claims.length} claims</b>${esc(t.transform.surface)}</div><div class="trace-step answer"><b>ANSWER</b>${esc(r.answer.surface)}</div>`;$('certificate-panel').textContent=JSON.stringify(r.certificate,null,2);renderModelOutputs(r)}
function bindTabs(){document.querySelectorAll('.arm-switch button').forEach(b=>b.onclick=()=>{state.arm=b.dataset.arm;document.querySelectorAll('.arm-switch button').forEach(x=>x.classList.toggle('active',x===b));render()});document.querySelectorAll('.audit-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.audit-tabs button').forEach(x=>x.classList.toggle('active',x===b));$('trace-panel').classList.toggle('hidden',b.dataset.tab!=='trace');$('certificate-panel').classList.toggle('hidden',b.dataset.tab!=='certificate')})}
function footer(){const a=state.data.artifacts;$('artifact-list').innerHTML=Object.entries(a).map(([k,v])=>`<div class="artifact">${esc(k)} → ${esc(v)}</div>`).join('');const reports=Object.values(state.data.evaluation).sort((a,b)=>`${a.evaluation_scope}.${a.model_id}.${a.prompt_mode}`.localeCompare(`${b.evaluation_scope}.${b.model_id}.${b.prompt_mode}`));if(!reports.length){$('evaluation-status').textContent='等待 SenseNova-SI / InternVL3 零训练评测。';return}$('evaluation-status').innerHTML=reports.map(r=>`<section class="eval-card"><div class="eval-title"><strong>${esc(modelName(r.model_id))} · ${esc(r.prompt_mode==='grounded_cot'?'Grounded-CoT':'Answer-only')}</strong><span>${esc(scopeName(r.evaluation_scope))} · n=${esc(r.evaluated)}</span></div><div class="eval-metrics"><span><b>${pct(r.accuracy)}</b>答案</span><span><b>${pct(r.semantic_accuracy)}</b>方向语义</span><span><b>${pct(r.trace_format_rate)}</b>三段齐全</span><span><b>${pct(r.joint_correct_trace_rate)}</b>答案∩三段</span></div>${Object.entries(r.by_task).map(([task,v])=>`<div class="eval-task"><span>${esc(taskName(task))}</span><b>${pct(v.accuracy)}</b><small>n=${esc(v.count)}</small></div>`).join('')}</section>`).join('')}
fetch(DATA_URL).then(r=>{if(!r.ok)throw new Error(`${r.status}`);return r.json()}).then(data=>{state.data=data;state.records=data.showcase_records;metrics();initFilters();bindTabs();footer()}).catch(err=>{$('readiness').textContent='DATA ERROR';$('readiness').className='status-chip blocked';$('record-title').textContent=`无法载入 ${DATA_URL}: ${err.message}`});
